services:
  web:
    build: .
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://coursera:coursera@coursera-mysql-instance2.cr2ygeme6l7y.us-east-1.rds.amazonaws.com:3306/blog_db
